version: '3.9'
services:
  nginx:
    image: nginx:latest
    container_name: production_nginx
    restart: unless-stopped
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./zhiva.crt:/etc/nginx/cert/cert.crt
      - ./zhiva.key:/etc/nginx/cert/cert.key
#      - ./logs:/var/log
    ports:
      - 8080:8080
      - 443:443
    networks:
      - pacs-network
    depends_on:
      - "orthanc-auth-service"
#    logging:
#      driver: none
  orthanc:
    image: jodogne/orthanc-plugins:1.11.0
    container_name: pacs_server
    command: /run/secrets/  # Path to the configuration files (stored as secrets)
    #    ports:
    #      - 4242:4242
    #      - 8042:8042
    secrets:
      - orthanc.json
    environment:
      - ORTHANC_NAME=Zhiva
      - VERBOSE_ENABLED=true
    volumes:
      - orthanc-db:/var/lib/orthanc/db/
      - ./zhiva.crt:/etc/orthanc/orthanc.crt
      - ./zhiva.key:/etc/orthanc/orthanc.key
      - ./trusted.crt:/etc/orthanc/trusted.crt
    networks:
      - pacs-network
    depends_on:
      - "orthanc-auth-service"
  orthanc-auth-service:
    build: ./auth-server
    container_name: auth_server
    # you should not expose port outside the docker network (only Orthanc needs to access it)
#    ports:
#      - 4000:4000
    environment:
      ZHIVA_MONGO_PATH: mongodb:27017
      ZHIVA_AUTH_PORT: ${ZHIVA_AUTH_PORT}
      ZHIVA_MONGO_DATABASE: ${ZHIVA_MONGO_DB}
      ZHIVA_MONGO_USER: ${ZHIVA_MONGO_USER}
      ZHIVA_MONGO_PASSWORD: ${ZHIVA_MONGO_PASSWORD}
      ZHIVA_AUTH_ALLOWED_ORIGINS: ${ZHIVA_AUTH_ALLOWED_ORIGINS}
      ZHIVA_AUTH_ADMIN_PASSWORD: ${ZHIVA_AUTH_ADMIN_PASSWORD}
    networks:
      - pacs-network
      - auth-network
    depends_on:
      - "mongodb"
    volumes:
      - ./jwt_priv.pem:/usr/src/app/dist/priv.pem
      - ./jwt_pub.pem:/usr/src/app/dist/pub.pem
      - ./auth-server/dist/:/usr/src/app/dist/
  mongodb:
    container_name: mongodb
    image: mongo:5.0
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${ZHIVA_MONGO_ADMIN}
      MONGO_INITDB_ROOT_PASSWORD: ${ZHIVA_MONGO_ADMIN_PASSWORD}
      MONGO_INITDB_DATABASE: ${ZHIVA_MONGO_DB}
      MONGO_INITDB_USER: ${ZHIVA_MONGO_USER}
      MONGO_INITDB_PWD: ${ZHIVA_MONGO_PASSWORD}
    networks:
      - auth-network
    volumes:
      - ./mongo/initdb.d/:/docker-entrypoint-initdb.d/
#      - mongodb:/data/db
    # you should not expose port outside the docker network
    # (only uncomment it if you want to connect to mongodb directly, neven in production)
    ports:
      - 27017:27017

secrets:
  orthanc.json:
    file: orthanc.json
volumes:
  orthanc-db:
  mongodb:
networks:
  pacs-network:
  auth-network: